name = "ChadStead"
author = "MrWaffle278"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c98a868caa27542262982ad86d4d668a024a0d0ce029e4480cac10032503bf61"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
