name = "ChadStead"
author = "MrWaffle278"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91c6aa6299c40be65f95f13e7d33afc24e1d9da17b44b133018772d8da534e53"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
