name = "ChadStead"
author = "MrWaffle278"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b282ea119deb8f74be5fcba16de7d3dcfd78aea8e3899b73686d12debd73acd7"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
